# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Wise piglet"
email: hemangsk@gmail.com
description: hints and advice for your journey
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lumizila.github.io/" # the base hostname & protocol for your site
github_username:  lumizila

# Build settings
markdown: kramdown
